### ISSUE TITLE
Bug: Fragments are not supported.

### ISSUE THREAD

**Issue by KonnorRogers** [whitefusionhq/graphtown#1]
```rb
graphql :docs do
  query {
    repository(owner: "rails", name: "webpacker") {
      object(expression: "master:docs/") {
        id
      }
    }
  }
end
```

The above is supported, however, if you try to use inline fragments, it breaks.

```rb
graphql :docs do
  query {
    repository(owner: "rails", name: "webpacker") {
      object(expression: "master:docs/") {
        id
        ... on Tree {
          entries {
             name
          }
        }
      }
    }
  }
end
```

Reproduction can be found here:

https://github.com/ParamagicDev/webpacker-docs-proxy/blob/1e696587787bea543b07b947ab9d013f42693aa7/plugins/builders/webpacker_docs.rb

**Comment by jaredcwhite** [comment]
@ParamagicDev I totally missed this before, my bad. Is this something that could be better served by a Heredoc rather than a Ruby block? See #2

**Comment by KonnorRogers** [comment]
@jaredcwhite perhaps. But if I remember correctly this was a limitation of the graphql dependency that Graphtown uses. Unfortunately, it's been a little while and I can't really remember.

**Comment by jaredcwhite** [comment]
Yeah, anything that actually handles the query itself would be in the Graphlient gem.
